version: "3.10"

services:
  db-menu-service:
    image: postgres:15
    networks:
      - "microservices"
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=menu
        - POSTGRES_PASSWORD=dbmenu2023
        - POSTGRES_DB=menu
        - POSTGRES_HOST_AUTH_METHOD=trust
  menu-service:
    image: douglasyakawe/menu-service:0.0.1
    networks:
      - "microservices"
    ports:
      - "8000:8000"
    environment:
        - POSTGRES_USER=menu
        - POSTGRES_PASSWORD=dbmenu2023
        - POSTGRES_SERVER=db-menu-service
        - POSTGRES_PORT=5432
        - POSTGRES_DB=menu
networks:
  microservices:
    external: true
